name: 'initialize'
description: 'Initialize action'

outputs:
  node_modules_cache_hit:
    description: 'Whether the node_modules cache was hit'
    value: ${{ steps.node_modules_cache_id.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'yarn'
    - name: cache node_modules
      id: node_modules_cache_id
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
