name: "initialize"
description: "Initialize action"

outputs:
  node_modules_cache_hit:
    description: "Whether the node_modules cache was hit"
    value: ${{ steps.node_modules_cache_id.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Get node version from volta
      id: get-node-version
      uses: keita-hino/get-node-version-from-volta@main
    - name: Corepack enable because yarn v4 is used
      shell: bash
      run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.get-node-version.outputs.nodeVersion }}
        cache: 'yarn'
    - name: cache node_modules
      id: node_modules_cache_id
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
