name: 'initialize'
description: 'Initialize action'

outputs:
  node_modules_cache_hit:
    description: 'Whether the node_modules cache was hit'
    value: ${{ steps.node_modules_cache_id.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version-file: 'package.json'
        cache: 'npm'
    - name: restore node_modules
      id: node_modules_cache_id
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies (fix optional dependencies bug)
      shell: bash
      run: npm install
